// <auto-generated />
using System;
using CarValueML.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarValueML.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CarValueML.Models.PredictionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Buying")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Doors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedPriceCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LugBoot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Maint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Persons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PredictedClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Safety")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
